# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Gaussian Blur Image Classification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Dependencies
      run: |
        python -m pip install numpy matplotlib opencv-python tensorflow Keras yolov9
    - name: Combine Weights
      run: |
        cat chunk_* > yolov.weights    
    - name: Gaussian Blur Image Classification
      run: |
        python GaussianBlurImageClassification.py
    - name: Add Files
      run: |
        git config --global user.email "ethan.pervere@gmail.com"
        git config --global user.name "ethanpvr18"
        git add plot.pdf
        git add yolov.weights
        git commit -m "Add files"
        git push https://ethanpvr18:${{ secrets.GH_PAT }}@github.com/ethanpvr18/Gaussian_Blur_Image_Classification.git
        





        
