# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Gaussian Blur Image Classification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Dependencies and Git Pull
      run: |
        git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ethanpvr18/senior_research.git
        python -m pip install numpy matplotlib opencv-python tensorflow Keras
    - name: Download YOLOv3 Weights and Config
      run: |
        wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg
        wget https://data.pjreddie.com/files/yolov3.weights
        # wget https://github.com/pjreddie/darknet/blob/master/data/coco.names
    - name: Gaussian Blur Image Classification
      run: |
        python GaussianBlurImageClassification_confidences.py
        python GaussianBlurImageClassification_times.py
        python GaussianBlurImageClassification.py
    - name: Commit and Push Artifacts
      if: github.actor != 'github-actions[bot]'
      run: |
        git config --global user.name "ethanpvr18"
        git config --global user.email "ethan.pervere@gmail.com"
        git lfs install
        git lfs track "plot.pdf" "plot_confidences.pdf" "plot_times.pdf" "modified/*.jpg"
        git add plot.pdf plot_confidences.pdf plot_times.pdf .gitattributes modified/*.jpg
        git commit -m "Add files with LFS" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ethanpvr18/senior_research.git





        
