# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install numpy
      run: |
        python -m pip install numpy
    - name: Install matplotlib
      run: |
        python -m pip install matplotlib
    - name: Install opencv-python
      run: |
        python -m pip install opencv-python
    - name: Install tensorflow==1.14.0
      run: |
        python -m pip install tensorflow==1.14.0  
    - name: Install Keras
      run: |
        python -m pip install Keras  
    - name: Install yolov3
      run: |
        python -m pip install yolov3  





        
